-- MySQL Script generated by MySQL Workbench
-- Thu Oct  3 22:21:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DBmercadinho
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DBmercadinho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBmercadinho` DEFAULT CHARACTER SET utf8 ;
USE `DBmercadinho` ;

-- -----------------------------------------------------
-- Table `DBmercadinho`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBmercadinho`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `senha` INT NOT NULL,
  `cargo` VARCHAR(10) NOT NULL,
  `acesso` TINYINT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBmercadinho`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBmercadinho`.`Produto` (
  `ean` VARCHAR(13) NOT NULL,
  `descricao` VARCHAR(20) NOT NULL,
  `tipoProduto` VARCHAR(20) NOT NULL,
  `unidade` VARCHAR(5) NOT NULL,
  `gramagem` INT NULL,
  `agranel` TINYINT NULL,
  `categoria` VARCHAR(15) NOT NULL,
  `marca` VARCHAR(20) NOT NULL,
  `custo` DECIMAL(4,2) NOT NULL,
  `lucro` DECIMAL(1,2) NOT NULL,
  `preco` DECIMAL(4,2) NOT NULL,
  `estoque` INT NULL,
  PRIMARY KEY (`ean`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBmercadinho`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBmercadinho`.`Venda` (
  `idVenda` INT NOT NULL,
  `valorVenda` DECIMAL(4,2) NOT NULL,
  `dataVenda` DATETIME NOT NULL,
  PRIMARY KEY (`idVenda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBmercadinho`.`MaquinaCartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBmercadinho`.`MaquinaCartao` (
  `idMaquineta` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(10) NOT NULL,
  `creditoTaxa` DECIMAL(1,2) NOT NULL,
  `debitoTaxa` DECIMAL(1,2) NOT NULL,
  `pixTaxa` DECIMAL(1,2) NULL,
  PRIMARY KEY (`idMaquineta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBmercadinho`.` Carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBmercadinho`.` Carrinho` (
  `Produto_ean` VARCHAR(13) NOT NULL,
  `Venda_idVenda` INT NOT NULL,
  `quantidadeVendida` INT NOT NULL,
  PRIMARY KEY (`Produto_ean`, `Venda_idVenda`),
  INDEX `fk_Produto_has_Venda_Venda1_idx` (`Venda_idVenda` ASC) VISIBLE,
  INDEX `fk_Produto_has_Venda_Produto_idx` (`Produto_ean` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Venda_Produto`
    FOREIGN KEY (`Produto_ean`)
    REFERENCES `DBmercadinho`.`Produto` (`ean`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Venda_Venda1`
    FOREIGN KEY (`Venda_idVenda`)
    REFERENCES `DBmercadinho`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBmercadinho`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBmercadinho`.`Pagamento` (
  `Venda_idVenda` INT NOT NULL,
  `dinheiro` DECIMAL(4,2) NULL,
  `pix` DECIMAL(4,2) NULL,
  `cartaoCredito` DECIMAL(4,2) NULL,
  `cartaoDebito` DECIMAL(4,2) NULL,
  `Pagamentocol` DECIMAL(4,2) NULL,
  PRIMARY KEY (`Venda_idVenda`),
  CONSTRAINT `fk_Pagamento_Venda1`
    FOREIGN KEY (`Venda_idVenda`)
    REFERENCES `DBmercadinho`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
